// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Aggressive localStorage cleanup - Remove ALL old app data
try {
  // Check if we have the old app data key
  const oldDataKey = 'devnovate_app_data';
  if (localStorage.getItem(oldDataKey)) {
    console.log('Found old localStorage data, removing...');
    localStorage.removeItem(oldDataKey);
    console.log('Old data removed successfully');
  }

  // Check total storage size
  const storageSize = JSON.stringify(localStorage).length;
  const sizeMB = storageSize / (1024 * 1024);
  
  console.log(`localStorage size: ${sizeMB.toFixed(2)}MB`);
  
  // If still too large, clear everything except Supabase auth
  if (sizeMB > 3) {
    console.log('localStorage too large, performing cleanup...');
    
    // Save Supabase auth tokens temporarily
    const authTokens: Record<string, string> = {};
    Object.keys(localStorage).forEach(key => {
      if (key.startsWith('sb-') && key.includes('auth-token')) {
        const value = localStorage.getItem(key);
        if (value) authTokens[key] = value;
      }
    });
    
    // Clear everything
    localStorage.clear();
    
    // Restore only auth tokens
    Object.entries(authTokens).forEach(([key, value]) => {
      try {
        localStorage.setItem(key, value);
      } catch (e) {
        console.error('Failed to restore auth token');
      }
    });
    
    console.log('localStorage cleaned up successfully');
  }
} catch (error) {
  console.error('Error cleaning localStorage:', error);
  // Last resort - clear everything
  try {
    localStorage.clear();
    console.log('Performed emergency localStorage clear');
  } catch (e) {
    console.error('Emergency clear failed');
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Custom storage adapter that handles quota errors
const customStorage = {
  getItem: (key: string) => {
    try {
      return localStorage.getItem(key);
    } catch (error) {
      console.error('localStorage getItem error:', error);
      return null;
    }
  },
  setItem: (key: string, value: string) => {
    try {
      localStorage.setItem(key, value);
    } catch (error) {
      console.error('localStorage setItem error:', error);
      // Clear old data and try again
      try {
        const keysToKeep = ['sb-', 'auth'];
        Object.keys(localStorage).forEach(k => {
          if (!keysToKeep.some(keep => k.includes(keep))) {
            localStorage.removeItem(k);
          }
        });
        localStorage.setItem(key, value);
      } catch (retryError) {
        console.error('localStorage retry failed:', retryError);
      }
    }
  },
  removeItem: (key: string) => {
    try {
      localStorage.removeItem(key);
    } catch (error) {
      console.error('localStorage removeItem error:', error);
    }
  }
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: customStorage as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});